language: java
install: true
jdk: oraclejdk8
env:
  matrix:
  - TERM=dumb
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo apt-get update -qq
  - sudo apt-get install oracle-java8-installer
before_script:
  - mvn --version
script: mvn install
